# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(default='Intro')),
                ('visi', models.TextField(default='Visi')),
                ('misi', models.TextField(default='Misi')),
                ('tujuan', models.TextField(default='Tujuan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_about', models.ImageField(blank=True, null=True, upload_to='images/staticpage')),
                ('slogan', models.CharField(default='Learn, Share, and Colleborate', max_length=50)),
                ('short_about', models.TextField(default='Tentang Siti dikit')),
                ('why_python', models.TextField(default='Karena Asyik')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyPythonPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(default='Pengenalan Python')),
                ('gambar_grafik', models.ImageField(blank=True, null=True, upload_to='images/staticpage')),
                ('isi', models.TextField(default='Inti deskripsi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
