# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpage', '0002_delete_whypythonpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='gambar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/staticpage'),
        ),
    ]
